#!/usr/bin/env bash
# This script diplays "Best School" 10 times using while loop.
# diplays "HI" on the 9th iteration.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
