#!/usr/bin/env bash
# This script displays numbers from 1 to 20.
# diplays "bad luck from China" on the 4th iteration.
# diplays "bad luck from Japan" on the 9th iteration
# diplays "bad luck from Italy" for the 17th loop other iteration.

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
